# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode8
xcode_sdk: iphonesimulator10.1
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
before_script:
  - carthage bootstrap --platform iOS
script:
  - set -o pipefail && xcodebuild -workspace 'RxSwiftExt.xcworkspace' -scheme 'RxSwiftExt' -configuration 'Debug' -sdk iphonesimulator -destination platform='iOS Simulator',OS='10.1',name='iPhone 7' build
  - set -o pipefail && xcodebuild -workspace 'RxSwiftExt.xcworkspace' -scheme 'RxSwiftExtTests' -configuration 'Debug' -sdk iphonesimulator -destination platform='iOS Simulator',OS='10.1',name='iPhone 7' test | xcpretty -c --test
